services:
  app:
    build: .  # Usa o Dockerfile do diretÔö£Ôöério atual
    container_name: casabela_app
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:1234@db:5432/casa-bela?schema=public
    depends_on:
      - db
    restart: always
    command: sh -c "npx prisma db push && npm run production"

  db:
    image: postgres:17
    container_name: casabela_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: casa-bela
    ports:
      - "5432:5432" # Libera a porta para vocÔö£┬¼ acessar via DBeaver/PgAdmin do seu PC
